version: '3'
services:
  db:
    image: 'postgres:14'
    container_name: "pg-docker"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'db1'
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
    networks:
      - my_network

  server:
    build: ./api
    ports:
      - "8080:8080"
    networks:
      - my_network
    volumes:
      - ./api:/app
    environment:
     DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/db1
    depends_on:
     - db
    # entrypoint: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]

  app:
    build: ./inventory-app
    ports:
      - "3000:3000"
    networks:
      - my_network
    volumes:
      - ./inventory-app:/src/app
    depends_on:
      - server

networks:
  my_network:
    driver: bridge